config/routes.rb
Bungee::Application.routes.draw do

  resources :users

  root 'pages#home'

  get 'contact', to: 'pages#contact'
  get 'about',   to: 'pages#about'
  get 'help',    to: 'pages#help'
  get 'signup',  to: 'users#new'

  get 'pages/home'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base

	attr_accessor   :password
	# should user strong_parameters to define accessible params
	#attr_accessible :name, :email, :password, :password_confirmation


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,  presence: true,
                      length: { maximum: 50 }

	validates :email, presence: true,
	                    format: { with: email_regex },
	                uniqueness: { case_sensitive: false }

	validates :password, presence: true,
	                 confirmation: true,
	                       length: { within: 6..40 }

	before_save :encrypt_password

  def has_password?(submitted_password)
  	self.encrypted_password == encrypt(submitted_password)
  end

  def User.authenticate(email, submitted_password)
  	user = self.find_by_email(email)
  	return nil  if user.nil?
  	return user if user.has_password?(submitted_password)
  end

	private
	  def encrypt_password
      self.salt = make_salt if self.new_record?
	  	self.encrypted_password = encrypt(self.password)
	  end

	  def encrypt(string)
	  	secure_hash("#{self.salt}--#{string}")
	  end

	  def secure_hash(string)
	  	Digest::SHA2.hexdigest(string)
	  end

	  def make_salt
	  	secure_hash("#{Time.now.utc}--#{self.password}")
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end

  def new
  	@title = "Sign up"
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	
  	if @user.save
  		redirect_to user_path(@user), flash: { success: "Welcome #{@user.name}" }
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis
	def title
		base_title = "Bungee App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def logo
		image_tag("logo.png", id: "home_page_logo",
			                   alt: "Bungee App")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
		<ul class="pager">
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Latest Update on Github", "https://github.com/hadibadjian/bungee" %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid">
  	<!-- Brand and toggle get grouped for better mobile display -->
  	<div class="navbar-header">
			<%= link_to logo, root_path %>
  	</div>

  	<!-- Collect the nav links, forms, and other content for toggling -->
  	<div class="collapse navbar-collapse">
	  	<ul class="pager navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Sign in", "#" %></li>
			</ul>
  	</div>
  </div>
</header>

app/views/layouts/_stylesheets.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag "bootstrap/bootstrap.min" %>
<%= javascript_include_tag "jquery/jquery-1.11.0.min" %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "bootstrap/bootstrap.min", media: "all" %>
<%= stylesheet_link_tag    "custom", media: "screen" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= render "layouts/stylesheets" %>
</head>
<body>
	<div class="container">
		<%= render "layouts/header" %>
		<section class="round">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Lorem ipsum</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Lorem ipsum</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Lorem ipsum</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Lorem ipsum</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Get Started", signup_path, class: "get_started_button" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	
	<div class="alert alert-danger">
		<h3>
			<%= pluralize(@user.errors.count, "error") %>
			prohibited this user from being saved:
		</h3>
		<p>There were problem with the following fields:</p>
		<table class="table table-condensed">
			<% @user.errors.full_messages.each do |message| %>
				<tr class="error">
					<td><small><%= message %></small></td>
				</tr>
			<% end %>
		</table>
	</div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<table class="table">
		<tr>
			<td><%= f.label :name %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td><%= f.label :email %></td>
			<td><%= f.text_field :email %></td>
		</tr>
		<tr>
			<td><%= f.label :password %></td>
			<td><%= f.password_field :password %></td>
		</tr>
		<tr>
			<td><%= f.label :password_confirmation, "Confirmation" %></td>
			<td><%= f.password_field :password_confirmation %></td>
		</tr>
		<tr>
			<td colspan="2">
				<%= f.submit "Sign up", class: "btn btn-info btn-large btn-block" %>
			</td>
		</tr>
	</table>
<% end %>

<p>Find me in app/views/users/new.html.erb</p> 

app/views/users/show.html.erb
<div>
	<div>
		<h1><%= @user.name %></h1>
	</div>
	<div class="sidebar">
		<strong>Name</strong> <%= @user.name %>
		<strong>URL</strong> <%= link_to user_path(@user), user_path(@user) %>
	</div>
</div>

<%= @user.name %>, <%= @user.email %>